# Generated by Django 4.1.6 on 2023-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_coupon_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
