# Generated by Django 4.2.1 on 2023-06-04 11:52

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_coupon_end_alter_coupon_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
