<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-06-13 08:52
=======
# Generated by Django 4.1.6 on 2023-06-12 21:08
>>>>>>> 45e7e15deef7eec2913aa907a6e15b9beb1df6fa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_coupon_end_alter_coupon_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
<<<<<<< HEAD
            field=models.CharField(max_length=200, null=True),
=======
            field=models.CharField(max_length=8, null=True),
>>>>>>> 45e7e15deef7eec2913aa907a6e15b9beb1df6fa
        ),
    ]
