# Generated by Django 4.1.6 on 2023-03-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_like_product_unlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
