# Generated by Django 4.1.6 on 2023-06-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_brand_product_color_product_size_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_favourite',
            field=models.IntegerField(default=0),
        ),
    ]
