# Generated by Django 4.1.6 on 2023-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_size_brand_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand_color',
            new_name='Band_color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_color',
            new_name='band_color',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='Brand_color_variant',
            new_name='Band_color_variant',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'none'), ('Band_color', 'band_color'), ('Color', 'color')], max_length=200, null=True),
        ),
    ]
