# Generated by Django 4.1.6 on 2023-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_brand_color_band_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Band_color',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='band_color',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='Band_color_variant',
            new_name='size_variant',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'none'), ('Size', 'size'), ('Color', 'color')], max_length=200, null=True),
        ),
    ]
