# Generated by Django 4.1.6 on 2023-07-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_product_change_remove_variant_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='change',
            field=models.BooleanField(default=True),
        ),
    ]
