# Generated by Django 4.1.6 on 2023-07-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_product_change_variant_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
