# Generated by Django 4.1.6 on 2023-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_product_comment_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_favourite',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
