# Generated by Django 4.1.6 on 2023-07-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_product_total_favourite_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
