# Generated by Django 4.1.6 on 2023-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
