# Generated by Django 4.1.6 on 2023-07-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
