# Generated by Django 4.1.6 on 2023-07-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment_num',
        ),
    ]
