# Generated by Django 4.1.6 on 2023-07-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_comment_comment_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_num',
        ),
    ]
