# Generated by Django 4.1.6 on 2023-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_comment_comment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
