# Generated by Django 4.1.6 on 2023-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_comment_comment_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_num',
        ),
        migrations.AddField(
            model_name='product',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
