# Generated by Django 4.1.6 on 2023-07-31 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0037_remove_comment_comment_num_product_comment_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment_num',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_num',
            field=models.ManyToManyField(blank=True, related_name='com_num', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='total_comment_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
