# Generated by Django 4.1.6 on 2023-07-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_product_comment_num_comment_comment_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='total_comment_num',
        ),
    ]
